name: superheroes
dependencies:
  - python=3.7
  - psycopg2
  - pip:
      - django==3.0.4
      - djangorestframework==3.11.0
      - django-filter==2.2.0
      - djangorestframework_simplejwt==4.4.0
      - markdown==3.2.1
      - markupsafe==1.1.1
      - coreapi==2.3.3
      - gunicorn
      - flake8
      - django-cors-headers