# Generated by Django 3.0.4 on 2020-03-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_like_to_post', to='post.Post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_like_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
